// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoIntegrador.Database;

namespace ProjetoIntegrador.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210616025844_primeiro")]
    partial class primeiro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoIntegrador.Models.Anotacao_Evento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("eventoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("eventoId");

                    b.ToTable("Anotacao_Evento");
                });

            modelBuilder.Entity("ProjetoIntegrador.Models.Anotacao_Lembrete", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("lembreteId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("lembreteId");

                    b.ToTable("Anotacao_Lembrete");
                });

            modelBuilder.Entity("ProjetoIntegrador.Models.Evento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("data_evento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasMaxLength(10000);

                    b.HasKey("id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("ProjetoIntegrador.Models.Lembrete", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("texto")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasMaxLength(10000);

                    b.HasKey("id");

                    b.ToTable("Lembretes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            data = new DateTime(2021, 6, 15, 22, 58, 43, 943, DateTimeKind.Local).AddTicks(1294),
                            texto = "Hoje foi um belo dia, espero que amanhã seja melhor!"
                        },
                        new
                        {
                            id = 2,
                            data = new DateTime(2021, 6, 15, 22, 58, 43, 945, DateTimeKind.Local).AddTicks(4123),
                            texto = "Hoje foi um dia comum, espero que amanhã seja melhor!"
                        },
                        new
                        {
                            id = 3,
                            data = new DateTime(2021, 6, 15, 22, 58, 43, 945, DateTimeKind.Local).AddTicks(4208),
                            texto = "Hoje foi um péssimo dia, espero que amanhã seja melhor!"
                        });
                });

            modelBuilder.Entity("ProjetoIntegrador.Models.Anotacao_Evento", b =>
                {
                    b.HasOne("ProjetoIntegrador.Models.Evento", "evento")
                        .WithMany("Anotacoes")
                        .HasForeignKey("eventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoIntegrador.Models.Anotacao_Lembrete", b =>
                {
                    b.HasOne("ProjetoIntegrador.Models.Lembrete", "lembrete")
                        .WithMany("Anotacoes")
                        .HasForeignKey("lembreteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
